# Uncomment this line to define a global platform for your project

platform :ios, '5.0'

podspec :path => "../CECDevice.podspec"

target "Demo" do
  pod "CECDevice", :path => "../"
end

# Uncomment the following lines to add testing dependencies
# target "DemoTests" do
#   pod 'Expecta'
# end




